### ISSUE TITLE
Error on decompressing an LZMA file (as opposed to an XZ file)

### ISSUE THREAD

**Issue by ttencate** [fpgaminer/rust-lzma#18]
The example code works fine for me; if I write the file using:

    let f = std::fs::File::create("/tmp/test.xz").unwrap();
    let mut f = lzma::LzmaWriter::new_compressor(f, 6).unwrap();
    write!(f, "Hello LZMA World!").unwrap();
    f.finish().unwrap();

(I'm new to Rust, so forgive me if my code has a weird accent.)

Then I can read it back in with:

    let file = std::fs::File::open("/tmp/test.xz").unwrap();
    let mut file = lzma::LzmaReader::new_decompressor(file).unwrap();
    let mut contents = String::new();
    file.read_to_string(&mut contents).expect("read failed");
    println!("{}", contents);

However, if I create a file on the command line:

    $ echo 'Hello LZMA World!' | lzma > /tmp/test.lzma
    $ lzmadec /tmp/test.lzma 
    Hello LZMA World!

Then the above reading code (with the file name changed, of course) fails:

    thread 'main' panicked at 'read failed: Custom { kind: Other, error: Format }', libcore/result.rs:1009:5

Indeed there is a difference between these two files:

    $ file /tmp/test.xz
    /tmp/test.xz: XZ compressed data
    $ file /tmp/test.lzma 
    /tmp/test.lzma: LZMA compressed data, streamed

Conversely, `lzmadec` can't read the `.xz` file:

    $ lzmadec /tmp/test.xz
    lzmadec: /tmp/test.xz: File format not recognized

So is the library mis-named? Can it actually read LZMA, as opposed to XZ? The compression algorithm is the same, but the container format is different.

It's worth noting that both my compiled Rust binary and `/usr/bin/lzma` are linked with `/usr/lib/liblzma.so.5`, so the functionality should be in there somewhere.

**Comment by fpgaminer** [comment]
The `lzma` command line tool uses the legacy format.  Quoting the man page:

> The native file format is the .xz format, but the legacy .lzma format used by LZMA  Utils  and  raw  compressed streams with no container format headers are also supported.

I made this crate to expose a simple Rust interface to the liblzma library.  Hence it just uses the default file format of liblzma (the .xz format).

Here are some details to hopefully clear up any confusion.  The command line tools `lzma` and `xz` are both part of the same project and package: XZ Utils.  They also use the same library, liblzma.  The difference is that `lzma` is a carry over from the legacy LZMA Utils project that XZ Utils evolved from.  During that evolution a new, more featured file format was introduced, as well as the improved LZMA2 compression.  Hence `xz` and the .xz format were born as the successor to `lzma` and .lzma.

`xz` can understand and produce files in the legacy format using the `--format=lzma` option.

As for rust-lzma, like I said it just uses the default format which the more modern `xz` tool understands by default.

The XZ Utils maintainers recommend _against_ using the legacy format.

If you have a specific reason to use the legacy format, and want to use that in rust, then it is possible to do but would require a slight update to rust-lzma.  It would need to call liblzma's `lzma_alone_encoder` instead of `lzma_easy_encoder` when initializing the stream (as well as the equivalent decoder function).

**Comment by ttencate** [comment]
Thank you for the detailed explanation! Maybe you could add the essential bits to the README, because right now it reads like "LZMA == XZ" which is clearly not the case.

I started looking into this because I need to process some 30 GB of CSV files compressed with the old LZMA format. I'm doing this with Python right now, but even using PyPy it's taking days.

Right now I've just thrown more hardware at the problem because it's a one-off thing, so this is far from critical for me. But I figured that something calling itself "rust-lzma", being unable to read a file called "lzma", would at least need some clarification in its docs, if not actual support for the format :)

**Comment by ttencate** [comment]
You are a gentlehuman and a scholar. It works perfectly now. Thank you so much for the quick fix!

**Comment by fpgaminer** [comment]
Awesome!

I'm closing the issue, but feel free to open it back up if I missed anything.
